# Generated by Django 6.0.3 on 2026-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/originals/"
                    ),
                ),
                (
                    "preview_mobile",
                    models.ImageField(blank=True, null=True, upload_to="blog/mobile/"),
                ),
                (
                    "preview_tablet",
                    models.ImageField(blank=True, null=True, upload_to="blog/tablets/"),
                ),
                (
                    "preview_desktop",
                    models.ImageField(blank=True, null=True, upload_to="blog/desktop/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_approve_blog", "Can approve blog")],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Категория"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Описание категории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/originals/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["-created_at"],
            },
        ),
    ]
